[workspace]

members = [
    "bot",
    "mal"
]

[patch.crates-io]
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "current" }
songbird = { git = "https://github.com/serenity-rs/songbird", branch = "current" }
